//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurso4_1try
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soldier
    {
        public int ID { get; set; }
        public Nullable<int> TTX_ID { get; set; }
        public Nullable<bool> Side { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<int> Defense { get; set; }
        public Nullable<bool> Alive { get; set; }
    
        public virtual Position Position1 { get; set; }
        public virtual TTX TTX { get; set; }
    }
}
