//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurso4_1try
{
    using System;
    using System.Collections.Generic;
    
    public partial class TTX
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TTX()
        {
            this.Soldier = new HashSet<Soldier>();
        }
    
        public int ID_TTX { get; set; }
        public Nullable<int> atk_primary_rad { get; set; }
        public Nullable<int> atk_secondary_rad { get; set; }
        public Nullable<bool> is_primary_percing_armor { get; set; }
        public Nullable<int> burst_length { get; set; }
        public Nullable<int> signature { get; set; }
        public Nullable<int> armor { get; set; }
        public Nullable<int> speed { get; set; }
        public Nullable<int> priority_for_enemy { get; set; }
        public Nullable<float> hit_chance_primary { get; set; }
        public Nullable<float> hit_chance_secondary { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Soldier> Soldier { get; set; }
    }
}
